apiVersion: apps/v1
kind: Deployment
metadata:
  name: module1-service
  namespace: var08
spec:
  replicas: 1
  selector:
    matchLabels:
      app: module1-service
  template:
    metadata:
      labels:
        app: module1-service
    spec:
      imagePullSecrets:
        - name: maria
      containers:
        - name: module1-service
          image: larinaaa1/myproject:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: db-credentials
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "1024Mi"