apiVersion: v1
kind: Service
metadata:
  name: additional-service-nodeport
  namespace: var08
spec:
  type: NodePort
  selector:
    app: additional-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31123